# Generated by Django 4.0.5 on 2022-08-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_crime_recordedby'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='record.prison'),
        ),
    ]
