# Generated by Django 4.0.5 on 2022-08-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_prison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='prison',
        ),
    ]
