# Generated by Django 4.0.5 on 2022-08-28 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0001_initial'),
        ('account', '0003_remove_user_prison'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prison.prison'),
        ),
    ]
