# Generated by Django 4.0.5 on 2022-08-28 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0002_delete_crime'),
        ('account', '0004_user_prison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prison.prison'),
        ),
    ]
