# Generated by Django 4.0.5 on 2022-09-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_prison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=251444444444, max_length=13, unique=True),
        ),
    ]
