# Generated by Django 4.1.1 on 2022-10-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_SuperManager',
            field=models.BooleanField(default=False),
        ),
    ]
