# Generated by Django 4.0.5 on 2022-08-28 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentralPrison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Amhara Prison commision', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrimeName', models.CharField(max_length=100)),
                ('Discription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrisonName', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prison.centralprison')),
            ],
        ),
    ]
