# Generated by Django 4.0.5 on 2022-08-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crime',
        ),
    ]
