# Generated by Django 4.1 on 2022-10-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0002_delete_crime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prison',
            name='Region',
            field=models.ForeignKey(choices=[('Amhara Prison Commision', 'Amhara Prison Commision')], null=True, on_delete=django.db.models.deletion.CASCADE, to='prison.centralprison'),
        ),
    ]
