# Generated by Django 4.1 on 2022-10-10 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0005_alter_centralprison_name_alter_prison_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prison',
            name='Region',
            field=models.ForeignKey(choices=[('Amhara Region Prison Police', 'Amhara Region Prison Police')], null=True, on_delete=django.db.models.deletion.CASCADE, to='prison.centralprison'),
        ),
    ]
