# Generated by Django 4.1 on 2022-10-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0006_alter_prison_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralprison',
            name='Name',
            field=models.CharField(default='Amhara Region Prison Police', max_length=100),
        ),
    ]
