# Generated by Django 4.1 on 2022-10-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0009_alter_centralprison_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prison',
            name='Region',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
