# Generated by Django 4.1 on 2022-10-10 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0010_alter_prison_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prison',
            name='Region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prison.centralprison'),
        ),
    ]
