# Generated by Django 4.0.5 on 2022-08-10 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentralPrison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Amhara Prison commision', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrimeName', models.CharField(max_length=100)),
                ('Discription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CriminalName', models.CharField(max_length=200, null=True)),
                ('Age', models.CharField(max_length=100, null=True)),
                ('Height', models.CharField(max_length=100, null=True)),
                ('EyeColor', models.CharField(max_length=100, null=True)),
                ('Gender', models.CharField(max_length=8, null=True)),
                ('Nationality', models.CharField(max_length=100, null=True)),
                ('CrimeDate', models.DateField(null=True)),
                ('ArrestedDate', models.DateField(null=True)),
                ('Gardian', models.CharField(max_length=100, null=True)),
                ('Bloodtype', models.CharField(max_length=30, null=True)),
                ('Imprisonment', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('Crime', models.ManyToManyField(to='record.crime')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Gender', models.CharField(max_length=8, null=True)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Nationality', models.CharField(max_length=200, null=True)),
                ('VisitDate', models.DateField(auto_now=True)),
                ('CriminalName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='record.criminal')),
            ],
        ),
        migrations.CreateModel(
            name='Prison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrisonName', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='record.centralprison')),
            ],
        ),
        migrations.AddField(
            model_name='criminal',
            name='PrisonName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='record.prison'),
        ),
    ]
