# Generated by Django 4.0.5 on 2022-08-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='recordedby',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
