# Generated by Django 4.0.5 on 2022-08-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_remove_crime_recordedby_crime_createdby_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prison',
            old_name='createdby',
            new_name='admin',
        ),
    ]
