# Generated by Django 4.0.5 on 2022-08-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_remove_prison_region_remove_prison_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminal',
            name='PrisonName',
        ),
    ]
