# Generated by Django 4.0.5 on 2022-08-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_criminal_prisonname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminal',
            name='PrisonName',
        ),
    ]
