# Generated by Django 4.1.1 on 2022-10-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_criminal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='Status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
