# Generated by Django 4.1.1 on 2022-10-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0013_criminal_status_alter_criminal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminal',
            name='Image',
        ),
    ]
