# Generated by Django 4.1 on 2022-10-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0014_remove_criminal_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criminal',
            old_name='ArrestedDate',
            new_name='EntranceDate',
        ),
        migrations.RenameField(
            model_name='criminal',
            old_name='Imprisonment',
            new_name='ImprisonmentTime',
        ),
        migrations.RenameField(
            model_name='criminal',
            old_name='CrimeDate',
            new_name='ReleasedDate',
        ),
        migrations.DeleteModel(
            name='Crime',
        ),
    ]
