# Generated by Django 4.1 on 2022-10-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0015_rename_arresteddate_criminal_entrancedate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criminal',
            old_name='Gardian',
            new_name='Guardian',
        ),
        migrations.RemoveField(
            model_name='criminal',
            name='Crime',
        ),
        migrations.AddField(
            model_name='criminal',
            name='AssignedCellNumber',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='Category',
            field=models.CharField(blank=True, choices=[('Criteria1', 'Criteria1'), ('Criteria2', 'Criteria2')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='criminal',
            name='CrimeDescription',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
