# Generated by Django 4.1 on 2022-10-11 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0011_alter_prison_region'),
        ('record', '0016_rename_gardian_criminal_guardian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='prison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prison.prison'),
        ),
    ]
