# Generated by Django 4.1 on 2022-10-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0017_visitor_prison'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='CriminalName',
            new_name='VisitedCriminal',
        ),
    ]
