# Generated by Django 4.1 on 2022-10-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0018_rename_criminalname_visitor_visitedcriminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminal',
            name='timeleft',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
