# Generated by Django 4.1 on 2022-10-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0019_criminal_timeleft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='ReleasedDate',
            field=models.DateTimeField(null=True),
        ),
    ]
