# Generated by Django 4.1 on 2022-10-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0020_alter_criminal_releaseddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='EntranceDate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='ReleasedDate',
            field=models.DateField(null=True),
        ),
    ]
