# Generated by Django 4.1 on 2022-10-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0021_alter_criminal_entrancedate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminal',
            name='timeleft',
        ),
    ]
