# Generated by Django 4.1 on 2022-10-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0023_criminal_timeleft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='timeleft',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
