# Generated by Django 4.1.1 on 2022-10-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0024_alter_criminal_timeleft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criminal',
            name='timeleft',
        ),
    ]
